{
  "imoveis": [
    {
      "id": 1,
      "codigo": "LC190",
      "tipo": "Apartamento",
      "bairro": "Jardim Europa",
      "areaUtil": 511,
      "areaTotal": 511,
      "dorms": 4,
      "suites": 4,
      "banheiros": 4,
      "vagas": 6,
      "preco": 40000000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Um por andar", "Varanda gourmet", "Closet", "Ar-condicionado", "Portaria 24hrs"],
      "tone": 0,
      "img": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 2,
      "codigo": "LC204",
      "tipo": "Casa",
      "bairro": "Jardim Europa",
      "areaUtil": 768,
      "areaTotal": 1419,
      "dorms": 5,
      "suites": 5,
      "banheiros": 5,
      "vagas": 6,
      "preco": 45000000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Churrasqueira", "Lareira", "Home office", "Sauna"],
      "tone": 1,
      "img": "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 3,
      "codigo": "LC178",
      "tipo": "Casa de condomínio",
      "bairro": "Cidade Jardim",
      "areaUtil": 1100,
      "areaTotal": 1100,
      "dorms": 4,
      "suites": 4,
      "banheiros": 4,
      "vagas": 7,
      "preco": 20000000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Academia", "Spa", "Portaria 24hrs", "Reformado"],
      "tone": 2,
      "img": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 4,
      "codigo": "LC221",
      "tipo": "Apartamento",
      "bairro": "Vila Nova Conceição",
      "areaUtil": 236,
      "areaTotal": 236,
      "dorms": 3,
      "suites": 3,
      "banheiros": 3,
      "vagas": 3,
      "preco": 7950000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": false,
      "caracteristicas": ["Varanda gourmet", "Academia", "Piscina", "Portaria 24hrs"],
      "tone": 3,
      "img": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 5,
      "codigo": "LC167",
      "tipo": "Apartamento",
      "bairro": "Jardim América",
      "areaUtil": 287,
      "areaTotal": 287,
      "dorms": 3,
      "suites": 2,
      "banheiros": 3,
      "vagas": 2,
      "preco": 7500000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Reformado", "Lareira", "Closet", "Ar-condicionado"],
      "tone": 4,
      "img": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 6,
      "codigo": "LC233",
      "tipo": "Casa",
      "bairro": "Cidade Jardim",
      "areaUtil": 950,
      "areaTotal": 2000,
      "dorms": 4,
      "suites": 3,
      "banheiros": 3,
      "vagas": 8,
      "preco": 16000000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Churrasqueira", "Home office", "Sauna"],
      "tone": 5,
      "img": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 7,
      "codigo": "LC245",
      "tipo": "Cobertura",
      "bairro": "Itaim Bibi",
      "areaUtil": 420,
      "areaTotal": 420,
      "dorms": 4,
      "suites": 4,
      "banheiros": 5,
      "vagas": 4,
      "preco": 18500000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Varanda gourmet", "Churrasqueira", "Um por andar"],
      "tone": 6,
      "img": "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 8,
      "codigo": "LC252",
      "tipo": "Apartamento",
      "bairro": "Jardim Paulistano",
      "areaUtil": 310,
      "areaTotal": 310,
      "dorms": 4,
      "suites": 3,
      "banheiros": 4,
      "vagas": 3,
      "preco": 9800000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": true,
      "caracteristicas": ["Academia", "Piscina", "Portaria 24hrs", "Varanda gourmet"],
      "tone": 7,
      "img": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 9,
      "codigo": "LC259",
      "tipo": "Cobertura",
      "bairro": "Vila Nova Conceição",
      "areaUtil": 550,
      "areaTotal": 550,
      "dorms": 4,
      "suites": 4,
      "banheiros": 6,
      "vagas": 5,
      "preco": 32000000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Spa", "Sauna", "Um por andar", "Mobiliado"],
      "tone": 0,
      "img": "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 10,
      "codigo": "LC264",
      "tipo": "Casa de condomínio",
      "bairro": "Alto de Pinheiros",
      "areaUtil": 680,
      "areaTotal": 900,
      "dorms": 5,
      "suites": 4,
      "banheiros": 5,
      "vagas": 6,
      "preco": 14500000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Churrasqueira", "Lareira", "Academia"],
      "tone": 1,
      "img": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 11,
      "codigo": "LC271",
      "tipo": "Apartamento",
      "bairro": "Itaim Bibi",
      "areaUtil": 198,
      "areaTotal": 198,
      "dorms": 3,
      "suites": 2,
      "banheiros": 3,
      "vagas": 2,
      "preco": 5900000,
      "operacao": "venda",
      "exclusivo": false,
      "lancamento": true,
      "caracteristicas": ["Academia", "Piscina", "Ar-condicionado", "Portaria 24hrs"],
      "tone": 2,
      "img": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80"
    },
    {
      "id": 12,
      "codigo": "LC280",
      "tipo": "Casa",
      "bairro": "Morumbi",
      "areaUtil": 820,
      "areaTotal": 1600,
      "dorms": 5,
      "suites": 5,
      "banheiros": 6,
      "vagas": 8,
      "preco": 12800000,
      "operacao": "venda",
      "exclusivo": true,
      "lancamento": false,
      "caracteristicas": ["Piscina", "Sauna", "Home office", "Churrasqueira", "Spa"],
      "tone": 3,
      "img": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80"
    }
  ],
  "bairros": [
    "Jardim Europa",
    "Jardim América",
    "Cidade Jardim",
    "Itaim Bibi",
    "Vila Nova Conceição",
    "Jardim Paulistano",
    "Morumbi",
    "Alto de Pinheiros"
  ],
  "tipos": [
    "Apartamento",
    "Casa",
    "Casa de condomínio",
    "Cobertura"
  ],
  "caracteristicas": [
    "Piscina",
    "Academia",
    "Churrasqueira",
    "Lareira",
    "Varanda gourmet",
    "Sauna",
    "Spa",
    "Portaria 24hrs",
    "Um por andar",
    "Mobiliado",
    "Reformado",
    "Home office",
    "Closet",
    "Ar-condicionado"
  ]
}
